/*-------------------------------------------------------------------------+
|                                                                          |
| Copyright 2012 Technische Universitaet Muenchen and                      |
| Fraunhofer-Institut fuer Experimentelles Software Engineering (IESE)     |
|                                                                          |
| Licensed under the Apache License, Version 2.0 (the "License");          |
| you may not use this file except in compliance with the License.         |
| You may obtain a copy of the License at                                  |
|                                                                          |
|    http://www.apache.org/licenses/LICENSE-2.0                            |
|                                                                          |
| Unless required by applicable law or agreed to in writing, software      |
| distributed under the License is distributed on an "AS IS" BASIS,        |
| WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. |
| See the License for the specific language governing permissions and      |
| limitations under the License.                                           |
|                                                                          |
+-------------------------------------------------------------------------*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.18 at 02:47:21 PM CET 
//


package de.quamoco.qm.docbook;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{}info.class" maxOccurs="unbounded"/>
 *       &lt;attGroup ref="{}articleinfo.attlist"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "graphicsAndMediaobjectsAndLegalnotices"
})
@XmlRootElement(name = "articleinfo")
public class Articleinfo {

    @XmlElementRefs({
        @XmlElementRef(name = "corpauthor", type = JAXBElement.class),
        @XmlElementRef(name = "issn", type = Issn.class),
        @XmlElementRef(name = "legalnotice", type = Legalnotice.class),
        @XmlElementRef(name = "abbrev", type = JAXBElement.class),
        @XmlElementRef(name = "citetitle", type = JAXBElement.class),
        @XmlElementRef(name = "pubdate", type = Pubdate.class),
        @XmlElementRef(name = "graphic", type = JAXBElement.class),
        @XmlElementRef(name = "personname", type = JAXBElement.class),
        @XmlElementRef(name = "publisher", type = Publisher.class),
        @XmlElementRef(name = "bibliocoverage", type = Bibliocoverage.class),
        @XmlElementRef(name = "seriesvolnums", type = Seriesvolnums.class),
        @XmlElementRef(name = "citebiblioid", type = Citebiblioid.class),
        @XmlElementRef(name = "corpname", type = Corpname.class),
        @XmlElementRef(name = "productname", type = JAXBElement.class),
        @XmlElementRef(name = "bibliomisc", type = Bibliomisc.class),
        @XmlElementRef(name = "abstract", type = Abstract.class),
        @XmlElementRef(name = "copyright", type = Copyright.class),
        @XmlElementRef(name = "date", type = Date.class),
        @XmlElementRef(name = "editor", type = Editor.class),
        @XmlElementRef(name = "lineage", type = Lineage.class),
        @XmlElementRef(name = "invpartnumber", type = Invpartnumber.class),
        @XmlElementRef(name = "honorific", type = Honorific.class),
        @XmlElementRef(name = "othername", type = Othername.class),
        @XmlElementRef(name = "printhistory", type = Printhistory.class),
        @XmlElementRef(name = "authorgroup", type = Authorgroup.class),
        @XmlElementRef(name = "titleabbrev", type = Titleabbrev.class),
        @XmlElementRef(name = "contrib", type = Contrib.class),
        @XmlElementRef(name = "authorinitials", type = JAXBElement.class),
        @XmlElementRef(name = "authorblurb", type = Authorblurb.class),
        @XmlElementRef(name = "volumenum", type = Volumenum.class),
        @XmlElementRef(name = "biblioset", type = Biblioset.class),
        @XmlElementRef(name = "orgname", type = JAXBElement.class),
        @XmlElementRef(name = "publishername", type = Publishername.class),
        @XmlElementRef(name = "ndxterm.class", type = NdxTerm2 .class),
        @XmlElementRef(name = "contractsponsor", type = Contractsponsor.class),
        @XmlElementRef(name = "artpagenums", type = Artpagenums.class),
        @XmlElementRef(name = "firstname", type = Firstname.class),
        @XmlElementRef(name = "pubsnumber", type = Pubsnumber.class),
        @XmlElementRef(name = "contractnum", type = Contractnum.class),
        @XmlElementRef(name = "address", type = JAXBElement.class),
        @XmlElementRef(name = "bibliosource", type = Bibliosource.class),
        @XmlElementRef(name = "pagenums", type = Pagenums.class),
        @XmlElementRef(name = "edition", type = Edition.class),
        @XmlElementRef(name = "affiliation", type = Affiliation.class),
        @XmlElementRef(name = "modespec", type = JAXBElement.class),
        @XmlElementRef(name = "confgroup", type = Confgroup.class),
        @XmlElementRef(name = "releaseinfo", type = Releaseinfo.class),
        @XmlElementRef(name = "title", type = Title.class),
        @XmlElementRef(name = "collab", type = Collab.class),
        @XmlElementRef(name = "subtitle", type = Subtitle.class),
        @XmlElementRef(name = "biblioid", type = Biblioid.class),
        @XmlElementRef(name = "keywordset", type = Keywordset.class),
        @XmlElementRef(name = "mediaobject", type = JAXBElement.class),
        @XmlElementRef(name = "subjectset", type = Subjectset.class),
        @XmlElementRef(name = "bibliorelation", type = Bibliorelation.class),
        @XmlElementRef(name = "isbn", type = Isbn.class),
        @XmlElementRef(name = "issuenum", type = Issuenum.class),
        @XmlElementRef(name = "productnumber", type = JAXBElement.class),
        @XmlElementRef(name = "author", type = JAXBElement.class),
        @XmlElementRef(name = "revhistory", type = JAXBElement.class),
        @XmlElementRef(name = "corpcredit", type = JAXBElement.class),
        @XmlElementRef(name = "itermset", type = Itermset.class),
        @XmlElementRef(name = "surname", type = Surname.class),
        @XmlElementRef(name = "othercredit", type = JAXBElement.class)
    })
    protected List<Object> graphicsAndMediaobjectsAndLegalnotices;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String role;
    @XmlAttribute(name = "lang")
    @XmlSchemaType(name = "anySimpleType")
    protected String attLang;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String revisionflag;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String vendor;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String condition;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String security;
    @XmlAttribute(name = "conformance")
    @XmlSchemaType(name = "NMTOKENS")
    protected List<String> conformances;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String wordsize;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String revision;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String os;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String arch;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String userlevel;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String xreflabel;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String remap;
    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlSchemaType(name = "anySimpleType")
    protected String base;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dir;

    /**
     * Gets the value of the graphicsAndMediaobjectsAndLegalnotices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the graphicsAndMediaobjectsAndLegalnotices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGraphicsAndMediaobjectsAndLegalnotices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Corpauthor }{@code >}
     * {@link Issn }
     * {@link Legalnotice }
     * {@link JAXBElement }{@code <}{@link Abbrev }{@code >}
     * {@link JAXBElement }{@code <}{@link Citetitle }{@code >}
     * {@link Pubdate }
     * {@link JAXBElement }{@code <}{@link Graphic }{@code >}
     * {@link JAXBElement }{@code <}{@link Personname }{@code >}
     * {@link Publisher }
     * {@link Bibliocoverage }
     * {@link Seriesvolnums }
     * {@link Citebiblioid }
     * {@link Corpname }
     * {@link JAXBElement }{@code <}{@link Productname }{@code >}
     * {@link Bibliomisc }
     * {@link Abstract }
     * {@link Copyright }
     * {@link Date }
     * {@link Editor }
     * {@link Lineage }
     * {@link JAXBElement }{@code <}{@link NdxTerm2Type }{@code >}
     * {@link Invpartnumber }
     * {@link Honorific }
     * {@link Othername }
     * {@link Printhistory }
     * {@link Authorgroup }
     * {@link Titleabbrev }
     * {@link Contrib }
     * {@link JAXBElement }{@code <}{@link Authorinitials }{@code >}
     * {@link Authorblurb }
     * {@link Volumenum }
     * {@link Biblioset }
     * {@link JAXBElement }{@code <}{@link Orgname }{@code >}
     * {@link Publishername }
     * {@link NdxTerm2 }
     * {@link Contractsponsor }
     * {@link Artpagenums }
     * {@link Firstname }
     * {@link Pubsnumber }
     * {@link Contractnum }
     * {@link JAXBElement }{@code <}{@link Address }{@code >}
     * {@link Bibliosource }
     * {@link Pagenums }
     * {@link Edition }
     * {@link Affiliation }
     * {@link JAXBElement }{@code <}{@link Modespec }{@code >}
     * {@link Confgroup }
     * {@link Releaseinfo }
     * {@link Title }
     * {@link Biblioid }
     * {@link Subtitle }
     * {@link Collab }
     * {@link Keywordset }
     * {@link JAXBElement }{@code <}{@link Mediaobject }{@code >}
     * {@link Subjectset }
     * {@link Bibliorelation }
     * {@link Isbn }
     * {@link Issuenum }
     * {@link JAXBElement }{@code <}{@link Productnumber }{@code >}
     * {@link JAXBElement }{@code <}{@link Author }{@code >}
     * {@link JAXBElement }{@code <}{@link Revhistory }{@code >}
     * {@link Itermset }
     * {@link JAXBElement }{@code <}{@link Corpcredit }{@code >}
     * {@link Surname }
     * {@link JAXBElement }{@code <}{@link Othercredit }{@code >}
     * 
     * 
     */
    public List<Object> getGraphicsAndMediaobjectsAndLegalnotices() {
        if (graphicsAndMediaobjectsAndLegalnotices == null) {
            graphicsAndMediaobjectsAndLegalnotices = new ArrayList<Object>();
        }
        return this.graphicsAndMediaobjectsAndLegalnotices;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

    /**
     * Gets the value of the attLang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttLang() {
        return attLang;
    }

    /**
     * Sets the value of the attLang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttLang(String value) {
        this.attLang = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the revisionflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevisionflag() {
        return revisionflag;
    }

    /**
     * Sets the value of the revisionflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevisionflag(String value) {
        this.revisionflag = value;
    }

    /**
     * Gets the value of the vendor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendor() {
        return vendor;
    }

    /**
     * Sets the value of the vendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendor(String value) {
        this.vendor = value;
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCondition(String value) {
        this.condition = value;
    }

    /**
     * Gets the value of the security property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurity() {
        return security;
    }

    /**
     * Sets the value of the security property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurity(String value) {
        this.security = value;
    }

    /**
     * Gets the value of the conformances property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the conformances property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConformances().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getConformances() {
        if (conformances == null) {
            conformances = new ArrayList<String>();
        }
        return this.conformances;
    }

    /**
     * Gets the value of the wordsize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWordsize() {
        return wordsize;
    }

    /**
     * Sets the value of the wordsize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWordsize(String value) {
        this.wordsize = value;
    }

    /**
     * Gets the value of the revision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevision() {
        return revision;
    }

    /**
     * Sets the value of the revision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevision(String value) {
        this.revision = value;
    }

    /**
     * Gets the value of the os property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOs() {
        return os;
    }

    /**
     * Sets the value of the os property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOs(String value) {
        this.os = value;
    }

    /**
     * Gets the value of the arch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArch() {
        return arch;
    }

    /**
     * Sets the value of the arch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArch(String value) {
        this.arch = value;
    }

    /**
     * Gets the value of the userlevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserlevel() {
        return userlevel;
    }

    /**
     * Sets the value of the userlevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserlevel(String value) {
        this.userlevel = value;
    }

    /**
     * Gets the value of the xreflabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXreflabel() {
        return xreflabel;
    }

    /**
     * Sets the value of the xreflabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXreflabel(String value) {
        this.xreflabel = value;
    }

    /**
     * Gets the value of the remap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemap() {
        return remap;
    }

    /**
     * Sets the value of the remap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemap(String value) {
        this.remap = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }

    /**
     * Gets the value of the dir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDir() {
        return dir;
    }

    /**
     * Sets the value of the dir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDir(String value) {
        this.dir = value;
    }

}
