/*-------------------------------------------------------------------------+
|                                                                          |
| Copyright 2012 Technische Universitaet Muenchen and                      |
| Fraunhofer-Institut fuer Experimentelles Software Engineering (IESE)     |
|                                                                          |
| Licensed under the Apache License, Version 2.0 (the "License");          |
| you may not use this file except in compliance with the License.         |
| You may obtain a copy of the License at                                  |
|                                                                          |
|    http://www.apache.org/licenses/LICENSE-2.0                            |
|                                                                          |
| Unless required by applicable law or agreed to in writing, software      |
| distributed under the License is distributed on an "AS IS" BASIS,        |
| WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. |
| See the License for the specific language governing permissions and      |
| limitations under the License.                                           |
|                                                                          |
+-------------------------------------------------------------------------*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.18 at 02:47:21 PM CET 
//


package de.quamoco.qm.docbook;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for inlineequation.content complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="inlineequation.content">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}alt" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element ref="{}graphic" maxOccurs="unbounded"/>
 *           &lt;element ref="{}inlinemediaobject" maxOccurs="unbounded"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "inlineequation.content", propOrder = {
    "alt",
    "inlinemediaobjects",
    "graphics"
})
@XmlSeeAlso({
    Inlineequation.class
})
public class InlineequationContent {

    protected Alt alt;
    @XmlElement(name = "inlinemediaobject")
    protected List<Inlinemediaobject> inlinemediaobjects;
    @XmlElement(name = "graphic")
    protected List<Graphic> graphics;

    /**
     * Gets the value of the alt property.
     * 
     * @return
     *     possible object is
     *     {@link Alt }
     *     
     */
    public Alt getAlt() {
        return alt;
    }

    /**
     * Sets the value of the alt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Alt }
     *     
     */
    public void setAlt(Alt value) {
        this.alt = value;
    }

    /**
     * Gets the value of the inlinemediaobjects property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inlinemediaobjects property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInlinemediaobjects().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Inlinemediaobject }
     * 
     * 
     */
    public List<Inlinemediaobject> getInlinemediaobjects() {
        if (inlinemediaobjects == null) {
            inlinemediaobjects = new ArrayList<Inlinemediaobject>();
        }
        return this.inlinemediaobjects;
    }

    /**
     * Gets the value of the graphics property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the graphics property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGraphics().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Graphic }
     * 
     * 
     */
    public List<Graphic> getGraphics() {
        if (graphics == null) {
            graphics = new ArrayList<Graphic>();
        }
        return this.graphics;
    }

}
