/*-------------------------------------------------------------------------+
|                                                                          |
| Copyright 2012 Technische Universitaet Muenchen and                      |
| Fraunhofer-Institut fuer Experimentelles Software Engineering (IESE)     |
|                                                                          |
| Licensed under the Apache License, Version 2.0 (the "License");          |
| you may not use this file except in compliance with the License.         |
| You may obtain a copy of the License at                                  |
|                                                                          |
|    http://www.apache.org/licenses/LICENSE-2.0                            |
|                                                                          |
| Unless required by applicable law or agreed to in writing, software      |
| distributed under the License is distributed on an "AS IS" BASIS,        |
| WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. |
| See the License for the specific language governing permissions and      |
| limitations under the License.                                           |
|                                                                          |
+-------------------------------------------------------------------------*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.18 at 02:47:21 PM CET 
//


package de.quamoco.qm.docbook;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;group ref="{}para.char.mix"/>
 *         &lt;group ref="{}tabentry.mix"/>
 *         &lt;element ref="{}table"/>
 *         &lt;element ref="{}informaltable"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{}td.attlist"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "td")
public class Td {

    @XmlElementRefs({
        @XmlElementRef(name = "synop.class", type = JAXBElement.class),
        @XmlElementRef(name = "informaltable", type = JAXBElement.class),
        @XmlElementRef(name = "gen.char.class", type = JAXBElement.class),
        @XmlElementRef(name = "ndxterm.class", type = NdxTerm2 .class),
        @XmlElementRef(name = "list.class", type = JAXBElement.class),
        @XmlElementRef(name = "mediaobject", type = JAXBElement.class),
        @XmlElementRef(name = "superscript", type = Superscript.class),
        @XmlElementRef(name = "xref.char.class", type = JAXBElement.class),
        @XmlElementRef(name = "beginpage", type = Beginpage.class),
        @XmlElementRef(name = "table", type = JAXBElement.class),
        @XmlElementRef(name = "admon.class", type = JAXBElement.class),
        @XmlElementRef(name = "subscript", type = Subscript.class),
        @XmlElementRef(name = "graphic", type = JAXBElement.class),
        @XmlElementRef(name = "link.char.class", type = JAXBElement.class),
        @XmlElementRef(name = "anchor", type = Anchor.class),
        @XmlElementRef(name = "inlineobj.char.class", type = JAXBElement.class),
        @XmlElementRef(name = "linespecific.class", type = JAXBElement.class),
        @XmlElementRef(name = "para.class", type = JAXBElement.class),
        @XmlElementRef(name = "docinfo.char.class", type = JAXBElement.class),
        @XmlElementRef(name = "remark", type = Remark.class),
        @XmlElementRef(name = "tech.char.class", type = JAXBElement.class)
    })
    @XmlMixed
    protected List<Object> content;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String abbr;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String axis;
    @XmlAttribute
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> headers;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String scope;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String rowspan;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String colspan;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String nowrap;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String bgcolor;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String width;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String height;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String valign;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String align;
    @XmlAttribute(name = "char")
    @XmlSchemaType(name = "anySimpleType")
    protected String _char;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String charoff;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String onclick;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String ondblclick;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String onmousedown;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String onmouseup;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String onmouseover;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String onmousemove;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String onmouseout;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String onkeypress;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String onkeydown;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String onkeyup;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "class")
    @XmlSchemaType(name = "anySimpleType")
    protected String clazz;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String style;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String title;
    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String lang;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Acronym }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Corpauthor }{@code >}
     * {@link JAXBElement }{@code <}{@link Token }{@code >}
     * {@link JAXBElement }{@code <}{@link Type }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Trademark }{@code >}
     * {@link JAXBElement }{@code <}{@link Para }{@code >}
     * {@link JAXBElement }{@code <}{@link Keycode }{@code >}
     * {@link JAXBElement }{@code <}{@link Biblioref }{@code >}
     * {@link JAXBElement }{@code <}{@link Citetitle }{@code >}
     * {@link JAXBElement }{@code <}{@link Graphic }{@code >}
     * {@link JAXBElement }{@code <}{@link Code }{@code >}
     * {@link JAXBElement }{@code <}{@link Personname }{@code >}
     * {@link JAXBElement }{@code <}{@link Command }{@code >}
     * {@link JAXBElement }{@code <}{@link Link }{@code >}
     * {@link JAXBElement }{@code <}{@link Exceptionname }{@code >}
     * {@link JAXBElement }{@code <}{@link Errortext }{@code >}
     * {@link JAXBElement }{@code <}{@link Firstterm }{@code >}
     * {@link JAXBElement }{@code <}{@link Xref }{@code >}
     * {@link JAXBElement }{@code <}{@link Variablelist }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Note }{@code >}
     * {@link JAXBElement }{@code <}{@link Database }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Productname }{@code >}
     * {@link JAXBElement }{@code <}{@link Methodname }{@code >}
     * {@link JAXBElement }{@code <}{@link Simplelist }{@code >}
     * {@link JAXBElement }{@code <}{@link Important }{@code >}
     * {@link JAXBElement }{@code <}{@link Envar }{@code >}
     * {@link JAXBElement }{@code <}{@link Glosslist }{@code >}
     * {@link JAXBElement }{@code <}{@link Ooclass }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Inlineequation }{@code >}
     * {@link JAXBElement }{@code <}{@link Screen }{@code >}
     * {@link JAXBElement }{@code <}{@link Hardware }{@code >}
     * {@link JAXBElement }{@code <}{@link Authorinitials }{@code >}
     * {@link JAXBElement }{@code <}{@link Guilabel }{@code >}
     * {@link JAXBElement }{@code <}{@link Interfacename }{@code >}
     * {@link JAXBElement }{@code <}{@link Destructorsynopsis }{@code >}
     * {@link JAXBElement }{@code <}{@link Symbol }{@code >}
     * {@link JAXBElement }{@code <}{@link Itemizedlist }{@code >}
     * {@link NdxTerm2 }
     * {@link JAXBElement }{@code <}{@link Glossterm }{@code >}
     * {@link JAXBElement }{@code <}{@link Computeroutput }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Tip }{@code >}
     * {@link JAXBElement }{@code <}{@link Filename }{@code >}
     * {@link JAXBElement }{@code <}{@link Parameter }{@code >}
     * {@link JAXBElement }{@code <}{@link Programlisting }{@code >}
     * {@link JAXBElement }{@code <}{@link Returnvalue }{@code >}
     * {@link JAXBElement }{@code <}{@link Screenco }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Modespec }{@code >}
     * {@link JAXBElement }{@code <}{@link Interface }{@code >}
     * {@link JAXBElement }{@code <}{@link Guiicon }{@code >}
     * {@link JAXBElement }{@code <}{@link Varname }{@code >}
     * {@link JAXBElement }{@code <}{@link Keysym }{@code >}
     * {@link JAXBElement }{@code <}{@link Mediaobject }{@code >}
     * {@link JAXBElement }{@code <}{@link Uri }{@code >}
     * {@link JAXBElement }{@code <}{@link Literal }{@code >}
     * {@link JAXBElement }{@code <}{@link Table }{@code >}
     * {@link JAXBElement }{@code <}{@link Function }{@code >}
     * {@link JAXBElement }{@code <}{@link Author }{@code >}
     * {@link JAXBElement }{@code <}{@link Inlinegraphic }{@code >}
     * {@link JAXBElement }{@code <}{@link Structname }{@code >}
     * {@link JAXBElement }{@code <}{@link Corpcredit }{@code >}
     * {@link JAXBElement }{@code <}{@link Userinput }{@code >}
     * {@link JAXBElement }{@code <}{@link Synopsis }{@code >}
     * {@link JAXBElement }{@code <}{@link Orderedlist }{@code >}
     * {@link JAXBElement }{@code <}{@link Segmentedlist }{@code >}
     * {@link JAXBElement }{@code <}{@link Option }{@code >}
     * {@link JAXBElement }{@code <}{@link Othercredit }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Errortype }{@code >}
     * {@link JAXBElement }{@code <}{@link Classname }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link Superscript }
     * {@link JAXBElement }{@code <}{@link Foreignphrase }{@code >}
     * {@link JAXBElement }{@code <}{@link Property }{@code >}
     * {@link JAXBElement }{@code <}{@link Sgmltag }{@code >}
     * {@link JAXBElement }{@code <}{@link Abbrev }{@code >}
     * {@link JAXBElement }{@code <}{@link Structfield }{@code >}
     * {@link JAXBElement }{@code <}{@link Markup }{@code >}
     * {@link JAXBElement }{@code <}{@link Optional }{@code >}
     * {@link JAXBElement }{@code <}{@link Classsynopsis }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Footnote }{@code >}
     * {@link JAXBElement }{@code <}{@link Warning }{@code >}
     * {@link JAXBElement }{@code <}{@link Informaltable }{@code >}
     * {@link JAXBElement }{@code <}{@link Fieldsynopsis }{@code >}
     * {@link JAXBElement }{@code <}{@link Methodsynopsis }{@code >}
     * {@link JAXBElement }{@code <}{@link Funcsynopsis }{@code >}
     * {@link JAXBElement }{@code <}{@link Keycombo }{@code >}
     * {@link JAXBElement }{@code <}{@link Olink }{@code >}
     * {@link String }
     * {@link JAXBElement }{@code <}{@link Wordasword }{@code >}
     * {@link Subscript }
     * {@link JAXBElement }{@code <}{@link Action }{@code >}
     * {@link JAXBElement }{@code <}{@link NdxTerm2Type }{@code >}
     * {@link JAXBElement }{@code <}{@link Citation }{@code >}
     * {@link JAXBElement }{@code <}{@link Menuchoice }{@code >}
     * {@link JAXBElement }{@code <}{@link Guimenu }{@code >}
     * {@link JAXBElement }{@code <}{@link Email }{@code >}
     * {@link JAXBElement }{@code <}{@link Oointerface }{@code >}
     * {@link JAXBElement }{@code <}{@link Ulink }{@code >}
     * {@link JAXBElement }{@code <}{@link Emphasis }{@code >}
     * {@link JAXBElement }{@code <}{@link Guibutton }{@code >}
     * {@link JAXBElement }{@code <}{@link Orgname }{@code >}
     * {@link JAXBElement }{@code <}{@link Cmdsynopsis }{@code >}
     * {@link Beginpage }
     * {@link JAXBElement }{@code <}{@link Inlinemediaobject }{@code >}
     * {@link JAXBElement }{@code <}{@link Constant }{@code >}
     * {@link JAXBElement }{@code <}{@link Phrase }{@code >}
     * {@link JAXBElement }{@code <}{@link Ooexception }{@code >}
     * {@link JAXBElement }{@code <}{@link Keycap }{@code >}
     * {@link JAXBElement }{@code <}{@link Medialabel }{@code >}
     * {@link JAXBElement }{@code <}{@link Citerefentry }{@code >}
     * {@link JAXBElement }{@code <}{@link Constructorsynopsis }{@code >}
     * {@link JAXBElement }{@code <}{@link Calloutlist }{@code >}
     * {@link JAXBElement }{@code <}{@link Systemitem }{@code >}
     * {@link JAXBElement }{@code <}{@link Application }{@code >}
     * {@link JAXBElement }{@code <}{@link Programlistingco }{@code >}
     * {@link JAXBElement }{@code <}{@link Screenshot }{@code >}
     * {@link JAXBElement }{@code <}{@link Formalpara }{@code >}
     * {@link JAXBElement }{@code <}{@link Package }{@code >}
     * {@link JAXBElement }{@code <}{@link Caution }{@code >}
     * {@link JAXBElement }{@code <}{@link Literallayout }{@code >}
     * {@link JAXBElement }{@code <}{@link Mousebutton }{@code >}
     * {@link JAXBElement }{@code <}{@link Errorname }{@code >}
     * {@link JAXBElement }{@code <}{@link Prompt }{@code >}
     * {@link JAXBElement }{@code <}{@link Productnumber }{@code >}
     * {@link JAXBElement }{@code <}{@link Bibliolist }{@code >}
     * {@link JAXBElement }{@code <}{@link Revhistory }{@code >}
     * {@link JAXBElement }{@code <}{@link Quote }{@code >}
     * {@link Anchor }
     * {@link JAXBElement }{@code <}{@link Guisubmenu }{@code >}
     * {@link Remark }
     * {@link JAXBElement }{@code <}{@link Errorcode }{@code >}
     * {@link JAXBElement }{@code <}{@link Footnoteref }{@code >}
     * {@link JAXBElement }{@code <}{@link Guimenuitem }{@code >}
     * {@link JAXBElement }{@code <}{@link Replaceable }{@code >}
     * {@link JAXBElement }{@code <}{@link Simpara }{@code >}
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the abbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbbr() {
        return abbr;
    }

    /**
     * Sets the value of the abbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbbr(String value) {
        this.abbr = value;
    }

    /**
     * Gets the value of the axis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAxis() {
        return axis;
    }

    /**
     * Sets the value of the axis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAxis(String value) {
        this.axis = value;
    }

    /**
     * Gets the value of the headers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the headers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHeaders().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getHeaders() {
        if (headers == null) {
            headers = new ArrayList<Object>();
        }
        return this.headers;
    }

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScope() {
        return scope;
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScope(String value) {
        this.scope = value;
    }

    /**
     * Gets the value of the rowspan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRowspan() {
        if (rowspan == null) {
            return "1";
        } else {
            return rowspan;
        }
    }

    /**
     * Sets the value of the rowspan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRowspan(String value) {
        this.rowspan = value;
    }

    /**
     * Gets the value of the colspan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColspan() {
        if (colspan == null) {
            return "1";
        } else {
            return colspan;
        }
    }

    /**
     * Sets the value of the colspan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColspan(String value) {
        this.colspan = value;
    }

    /**
     * Gets the value of the nowrap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNowrap() {
        return nowrap;
    }

    /**
     * Sets the value of the nowrap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNowrap(String value) {
        this.nowrap = value;
    }

    /**
     * Gets the value of the bgcolor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBgcolor() {
        return bgcolor;
    }

    /**
     * Sets the value of the bgcolor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBgcolor(String value) {
        this.bgcolor = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidth(String value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeight(String value) {
        this.height = value;
    }

    /**
     * Gets the value of the valign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValign() {
        return valign;
    }

    /**
     * Sets the value of the valign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValign(String value) {
        this.valign = value;
    }

    /**
     * Gets the value of the align property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlign() {
        return align;
    }

    /**
     * Sets the value of the align property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlign(String value) {
        this.align = value;
    }

    /**
     * Gets the value of the char property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChar() {
        return _char;
    }

    /**
     * Sets the value of the char property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChar(String value) {
        this._char = value;
    }

    /**
     * Gets the value of the charoff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCharoff() {
        return charoff;
    }

    /**
     * Sets the value of the charoff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCharoff(String value) {
        this.charoff = value;
    }

    /**
     * Gets the value of the onclick property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnclick() {
        return onclick;
    }

    /**
     * Sets the value of the onclick property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnclick(String value) {
        this.onclick = value;
    }

    /**
     * Gets the value of the ondblclick property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOndblclick() {
        return ondblclick;
    }

    /**
     * Sets the value of the ondblclick property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOndblclick(String value) {
        this.ondblclick = value;
    }

    /**
     * Gets the value of the onmousedown property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnmousedown() {
        return onmousedown;
    }

    /**
     * Sets the value of the onmousedown property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnmousedown(String value) {
        this.onmousedown = value;
    }

    /**
     * Gets the value of the onmouseup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnmouseup() {
        return onmouseup;
    }

    /**
     * Sets the value of the onmouseup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnmouseup(String value) {
        this.onmouseup = value;
    }

    /**
     * Gets the value of the onmouseover property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnmouseover() {
        return onmouseover;
    }

    /**
     * Sets the value of the onmouseover property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnmouseover(String value) {
        this.onmouseover = value;
    }

    /**
     * Gets the value of the onmousemove property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnmousemove() {
        return onmousemove;
    }

    /**
     * Sets the value of the onmousemove property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnmousemove(String value) {
        this.onmousemove = value;
    }

    /**
     * Gets the value of the onmouseout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnmouseout() {
        return onmouseout;
    }

    /**
     * Sets the value of the onmouseout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnmouseout(String value) {
        this.onmouseout = value;
    }

    /**
     * Gets the value of the onkeypress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnkeypress() {
        return onkeypress;
    }

    /**
     * Sets the value of the onkeypress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnkeypress(String value) {
        this.onkeypress = value;
    }

    /**
     * Gets the value of the onkeydown property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnkeydown() {
        return onkeydown;
    }

    /**
     * Sets the value of the onkeydown property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnkeydown(String value) {
        this.onkeydown = value;
    }

    /**
     * Gets the value of the onkeyup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnkeyup() {
        return onkeyup;
    }

    /**
     * Sets the value of the onkeyup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnkeyup(String value) {
        this.onkeyup = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStyle() {
        return style;
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStyle(String value) {
        this.style = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

}
